version: 0.2

phases:
  install:
    commands:
      - echo "Installing Python"
      - python3 --version
  build:
    commands:
      - echo "Running Python app..."
      - python3 app.py

artifacts:
  files:
    - '**/*'
